version: '3.8'

services:
  # Web Application Service
  app:
    # Must use image from Docker Hub instead of building directly
    image: dinhquoccuong286/product-api:latest 
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/products_db
      - PORT=3000
    restart: always # Auto restart on failure or reboot
    depends_on:
      - mongodb
    volumes:
      # Volume for uploaded images to prevent data loss 
      - ./uploads:/usr/src/app/public/uploads

  # Database Service
  mongodb:
    image: mongo:7.0 # Use official image
    # Note: Port mapping 27017 can be omitted if external access is not needed, improving security
    restart: always
    volumes:
      - mongo-data:/data/db # Volume for database data

# Declare used Volumes
volumes:
  mongo-data:
